typography_spectrum: 0.36891598417423666
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0.375
  rhythmicContrast: 0.9900085253175348
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.81149
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Pravaha films
  email: ''
  url: 'http://thegrid.ai/pravaha-films/'
name: Sit Beside Me
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: sit beside me
purpose: []
