typography_spectrum: 0.36891598417423666
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.81149
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Pravaha films
  email: ''
  url: 'http://thegrid.ai/pravaha-films/'
name: Sit Beside Me
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - id: 15f719a5-f2b8-42b8-a09d-0cb0481076bf
    url: 2016-06-15-sit-beside-me-or-sientate-junto-a-mi.html
    name: view film
    type: content
  - id: b9bf0802-491b-4184-bd83-1092e7add5c5
    url: 2016-06-01-b9bf0802-491b-4184-bd83-1092e7add5c5.html
    name: gallery
    type: content
  - id: 47ee791e-bb52-4b50-a746-1fdbf8a0306a
    url: 2016-06-01-press-kit.html
    name: press kit
    type: content
favicon: null
title: sit beside me
purpose: []
