typography_spectrum: 0.6499382245820016
color:
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  brandStrength: 0.42530259885825217
  lightness: 0.2110294837038964
  saturation: 0.9708329641725868
  rhythmicContrast: 0.03632222185842693
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4936668847221881
analytics:
  google: UA-81046230-1
  facebook: null
  twitter: null
author:
  name: ''
  email: ''
  url: ''
name: SitBesideMe
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: view film
    id: 4b58e0f2-c2e1-4109-9648-c4b87b8cb149
    type: content
  - name: about
    id: 80d1a683-0a32-4672-865c-f23c21d37509
    type: content
  - name: gallery
    id: b9bf0802-491b-4184-bd83-1092e7add5c5
    type: content
  - name: press kit
    id: 47ee791e-bb52-4b50-a746-1fdbf8a0306a
    type: content
  - name: home
    id: 03b98cfb-d861-4405-ac06-0978c0d72e3c
    type: content
favicon: null
title: sit beside me
purpose: []
