name: Sit Beside Me
favicon: null
layout_spectrum: 0.81149
typography_spectrum: 0.36891598417423666
author:
  name: Pravaha films
  email: ''
  url: 'http://thegrid.ai/pravaha-films/'
navigation: []
title: sit beside me
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-81046230-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.75
purpose: []
