typography_spectrum: 0.36891598417423666
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.81149
analytics:
  google: UA-81046230-1
  facebook: null
  twitter: null
author:
  name: ''
  email: ''
  url: 'http://thegrid.ai/pravaha-films/'
name: SitBesideMe
cta:
  domain: null
  bucket: null
  version: null
navigation: []
favicon: null
title: ''
purpose: []
