typography_spectrum: 0.36891598417423666
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.5496767114382237
  lightness: 0.6039688899181783
  saturation: 0.5163080380298197
  rhythmicContrast: 0.9900085253175348
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.25787158170714974
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: ''
  email: ''
  url: ''
name: Sit Beside Me
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: sit beside me
purpose: []
