name: Sit Beside Me
favicon: null
layout_spectrum: 0.5759744802489877
typography_spectrum: 0.8324584597721696
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.11001641675829887
  lightness: 0.8151448222342879
  saturation: 0.0003257002681493759
  rhythmicContrast: 0.0017077864613384008
purpose: []
