typography_spectrum: 0.9640714786946774
content_rating:
  adult: false
color:
  brandColors:
    - '#F9E4AD'
    - '#E6B098'
    - '#CC4452'
    - '#723147'
    - '#31152B'
  brandStrength: 0.8606205570977181
  lightness: 0.8360089610796422
  saturation: 0.2903486010618508
  rhythmicContrast: 0.13662005541846156
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.019967122934758663
analytics:
  google: UA-81046230-1
author:
  name: ''
  url: 'http://prameni.org'
  email: info@prameni.org
name: SitBesideMe
cta: {}
navigation:
  - name: home
    id: 03b98cfb-d861-4405-ac06-0978c0d72e3c
    type: content
  - name: gallery
    id: b9bf0802-491b-4184-bd83-1092e7add5c5
    type: content
  - name: press kit
    id: 47ee791e-bb52-4b50-a746-1fdbf8a0306a
    type: content
  - name: contact
    id: 0a20d189-f171-4aed-945b-423bee0d4a42
    type: content
  - name: view film
    id: f1971c85-f18f-46ea-b123-347d23f38b5a
    type: content
title: ''
purpose: []
