name: Sit Beside Me
favicon: null
layout_spectrum: 0.00674
typography_spectrum: 1
title: sit beside me
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8e3017'
    - '#462a1c'
    - '#090907'
    - '#a2623f'
    - '#677f79'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.75
purpose: []
