typography_spectrum: 0.36891598417423666
color:
  brandColors:
    - '#FF6138'
    - '#FFFF9D'
    - '#BEEB9F'
    - '#79BD8F'
    - '#00A388'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.0625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.81149
analytics:
  google: UA-81046230-1
  facebook: null
  twitter: null
author:
  name: Pravaha films
  email: ''
  url: 'http://thegrid.ai/pravaha-films/'
name: Sit Beside Me
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: about
    id: 80d1a683-0a32-4672-865c-f23c21d37509
    type: content
  - name: press kit
    id: 47ee791e-bb52-4b50-a746-1fdbf8a0306a
    type: content
  - name: view film
    id: 15f719a5-f2b8-42b8-a09d-0cb0481076bf
    type: content
favicon: null
title: sit beside me
purpose: []
