name: SitBesideMe
favicon: null
layout_spectrum: 0.4936668847221881
typography_spectrum: 0.6499382245820016
author:
  name: ''
  email: ''
  url: ''
navigation: []
title: sit beside me
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-81046230-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
  brandStrength: 0.42530259885825217
  lightness: 0.2110294837038964
  saturation: 0.9708329641725868
  rhythmicContrast: 0.03632222185842693
purpose: []
