typography_spectrum: 1
color:
  brandColors:
    - '#8e3017'
    - '#462a1c'
    - '#090907'
    - '#a2623f'
    - '#677f79'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 1
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.00674
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Jenne Magno
  email: jennemagno@gmail.com
name: Sit Beside Me
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: sit beside me
purpose: []
